<?php

namespace bonP\dealBundle\Repository;

/**
 * DealRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DealRepository extends \Doctrine\ORM\EntityRepository
{
    public function findActivedeals($id)
    {
        $q = $this->getEntityManager()->createQuery("Select d from bonPdealBundle:Deal d JOIN d.enseigne enseigne JOIN enseigne.user u where d.active=1 AND u.id!=:id ORDER BY d.nom ASC ")->setParameter('id',$id);
        return $q->getResult() ;
    }
    public function findmydeals($a)
    {
        $q = $this->getEntityManager()->createQuery("SELECT d FROM bonPdealBundle:Deal d JOIN d.enseigne enseigne JOIN enseigne.user u WHERE u.id=:a ORDER BY d.visite DESC ")->setParameter('a',$a->getId());
        return $q->getResult();
    }
    public function findscore($score,$id)
    {
        $q = $this->getEntityManager()->createQuery("SELECT d FROM bonPdealBundle:Deal d JOIN d.enseigne enseigne JOIN enseigne.user u WHERE d.score <=:score and u.id!=:id  ORDER BY d.score DESC ")->setParameter('score',$score)->setParameter('id',$id);
        return $q->getResult();

    }
    public function findcategorie($categorie,$id)
    {
        $q = $this->getEntityManager()->createQuery("SELECT d FROM bonPdealBundle:Deal d JOIN d.enseigne enseigne JOIN enseigne.categorie u JOIN enseigne.user uu WHERE u.nom=:categorie and uu.id!=:id  ORDER BY d.visite DESC ")->setParameter('categorie',$categorie)->setParameter('id',$id);
        return $q->getResult();
    }
    public function findville($ville,$id)
    {
        $q = $this->getEntityManager()->createQuery("SELECT d FROM bonPdealBundle:Deal d JOIN d.enseigne enseigne JOIN enseigne.adresse adr JOIN enseigne.user u WHERE adr.ville LIKE :ville and u.id!=:id ORDER BY d.visite DESC ")->setParameter('ville','%'.$ville.'%')->setParameter('id',$id);
        return $q->getResult();
    }
    public function nbrdealville ()
    {
        $q = $this->getEntityManager()->createQuery("SELECT COUNT (d) AS nbr, adresse.ville FROM bonPdealBundle:Deal d JOIN d.enseigne enseigne JOIN enseigne.adresse adresse GROUP BY adresse.ville");
        return $q->getResult();
    }
    public function nbrdealenseigne()
    {
        $q = $this->getEntityManager()->createQuery("SELECT COUNT (d) AS nbr, enseigne.nom FROM bonPdealBundle:Deal d JOIN d.enseigne enseigne GROUP BY enseigne.nom");
        return $q->getResult();
    }

    public function finduscore($score)
    {
        $q = $this->getEntityManager()->createQuery("Select u from bonPuserBandle:User u where u.score>=:score")->setParameter('score',$score);
        return $q->getResult() ;
    }
    public function finddate($dd)
    {
        $q = $this->getEntityManager()->createQuery("SELECT d FROM bonPdealBundle:Deal d WHERE d.datefin<:dd")->setParameter('dd',$dd);
        return $q->getResult();
    }



}
