<?php

namespace bonP\dealBundle\Repository;

/**
 * ReservationdealRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReservationdealRepository extends \Doctrine\ORM\EntityRepository
{
    public function findReservation($id)
    {
        $q = $this->getEntityManager()->createQuery("Select r from bonPdealBundle:Reservationdeal r JOIN r.user u WHERE u.id=:id ")->setParameter('id',$id);
        return $q->getResult() ;
    }
    public function nbrreservationdeal ()
    {
        $q = $this->getEntityManager()->createQuery("SELECT COUNT (r) AS nbr, deal.nom As nom FROM bonPdealBundle:Reservationdeal r JOIN r.deal deal GROUP BY deal.nom");
        return $q->getResult();
    }
    public function nbrreservationenseigne()
    {
        $q = $this->getEntityManager()->createQuery("SELECT COUNT (r) AS nbr, enseigne.nom As nom FROM bonPdealBundle:Reservationdeal r JOIN r.deal deal JOIN deal.enseigne enseigne GROUP BY enseigne.nom");
        return $q->getResult();
    }
}
