<?php

namespace bonP\badgeBundle\Repository;

/**
 * CommentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommentRepository extends \Doctrine\ORM\EntityRepository
{

    public function countForUser($user_id)
    {
            return $this->createQueryBuilder('c')
                ->select('c.id')
                ->where('c.user = :user')
                ->setParameter('user',$user_id)
                ->getQuery()
                ->getResult();
    }
    public function findDealComments($id)
    {
        $q = $this->getEntityManager()->createQuery("Select p from bonPbadgeBundle:Comment p where p.deal=:id")->setParameter('id',$id);
        return $q->getResult() ;
    }
}
