<?php

namespace bonP\planBundle\Repository;

/**
 * CategorieRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategorieRepository extends \Doctrine\ORM\EntityRepository
{
    public function findcat()
    {
        $q = $this->getEntityManager()->createQuery("SELECT a FROM bonPplanBundle:Categorie a");
        return $q->getResult();
    }
}
