<?php

namespace bonP\planBundle\Repository;

/**
 * CommentaireRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommentaireRepository extends \Doctrine\ORM\EntityRepository
{


    public function findreportedcomments()
    {
        $q = $this->getEntityManager()->createQuery("Select c from planBundle:Commentaire c where c.reported=true ORDER BY c.reportnumber DESC ");
        return $q->getResult() ;
    }

}
