<?php

namespace bonP\planBundle\Repository;

/**
 * PlanRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PlanRepository extends \Doctrine\ORM\EntityRepository
{
    public function findActivePlans()
    {
        $q = $this->getEntityManager()->createQuery("Select p from planBundle:Plan p where p.active=1 and p.reported=0 ");
        return $q->getResult() ;
    }

    public function findmyPlans($username)
    {
        $q = $this->getEntityManager()->createQuery("Select p from planBundle:Plan p where p.prop=:username")->setParameter('username',$username);
        return $q->getResult() ;
    }

    public function findInactivePlans()
    {
        $q = $this->getEntityManager()->createQuery("Select p from planBundle:Plan p where p.active=0 ORDER BY p.dateAjout DESC ");
        return $q->getResult() ;
    }

    public function findByCategorie($cat)
    {
        $q = $this->getEntityManager()->createQuery("Select p from planBundle:Plan p JOIN p.genre categorie where categorie.nom=:cat and p.active=1 ORDER BY p.score DESC ")->setParameter("cat",$cat);
        return $q->getResult() ;
    }

    public function findreportedPlans()
    {
        $q = $this->getEntityManager()->createQuery("Select p from planBundle:Plan p where p.reported=true ORDER BY p.reportnumber DESC ");
        return $q->getResult() ;
    }


    public function findmostviewedPlans()
    {
        $q = $this->getEntityManager()->createQuery("Select p from planBundle:Plan p where p.reported=false  ORDER BY p.score DESC ")->setMaxResults(4);
        return $q->getResult();

    }
        public function findTitre($titre)
    {
        $q = $this->getEntityManager()->createQuery("SELECT p FROM planBundle:Plan p WHERE p.titre LIKE :titre ORDER BY p.score DESC ")->setParameter('titre','%'.$titre.'%');
        return $q->getResult();
    }

}
