<?php

namespace bonP\reservationBundle\Repository;

/**
 * ReservationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReservationRepository extends \Doctrine\ORM\EntityRepository
{
    public function findens($ens)
    {
        $q = $this->getEntityManager()->createQuery("SELECT r FROM bonPreservationBundle:Reservation r JOIN r.enseigne enseigne WHERE enseigne.nom LIKE :ens")->setParameter('ens','%'.$ens.'%');
        return $q->getResult();
    }
}
