<?php

namespace bonP\reservationBundle\Repository;
use bonP\enseigneBundle\Entity\Enseigne;
use bonP\enseigneBundle\Entity\Evenement;
use bonP\reservationBundle\Entity\ReservationEvenement;

/**
 * ReservationEventRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReservationEventRepository extends \Doctrine\ORM\EntityRepository
{
    public function reservationEvenementAction($id,$capacité)
    {


        $em = $this->getDoctrine()->getManager();
        $event=$em->getRepository(Evenement::class)->find($id);
        if ($event->getEnseigne->getCapacite() >= $capacité)
        {
            $res = new ReservationEvenement();
            $res->setEvenement($event);
            $res->setNombrplaces($capacité);
            $user = $this->container->get('security.token_storage')->getToken()->getUser();
            $res->setUser($user);

            $em->persist($res);
            return $this->redirectToRoute();
        }
        return $this->redirectToRoute('');
    }
    public function findeven($nomE)
    {
        $q = $this->getEntityManager()->createQuery("SELECT r FROM bonPreservationBundle:ReservationEvenement r JOIN r.evenement enseigne WHERE enseigne.nom LIKE :ens")->setParameter('ens','%'.$nomE.'%');
        return $q->getResult();
    }
}
