<?php

namespace bonP\userBundle\Repository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends \Doctrine\ORM\EntityRepository
{
    public function finduscore($score)
    {
        $q = $this->getEntityManager()->createQuery("Select u from bonPuserBundle:User u where u.score>=:score")->setParameter('score',$score);
        return $q->getResult() ;
    }
}
